FROM registry:5000/stemmarest-final-base

COPY stemmarest.war /usr/local/tomcat/webapps/
COPY server.xml /usr/local/tomcat/conf/
COPY tomcat-users.xml /usr/local/tomcat/conf/

EXPOSE 8080
CMD ["catalina.sh", "run"]
