FROM tomcat:8.0-jre8
LABEL maintainer=ops@dh.univie.ac.at \
      vendor=DHUniWien \

RUN apt-get update && apt-get install --yes \
    graphviz \
    tomcat8 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/lib/stemmarest \
 && chown -R tomcat8. /var/lib/stemmarest \
 && chmod -R g+w /var/lib/stemmarest \
 && chmod -R +2000 /var/lib/stemmarest

ENV STEMMAREST_HOME /var/lib/stemmarest/
