name: Docker

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - '[0-9]*'

jobs:
  # Build artifacts, skip tests since they should already be known to pass
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Add Miredot license
      run: sed -i "s/MIREDOT_LICENSE/${{ secrets.MIREDOT_LICENSE }}/" pom.xml
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
    - name: Archive .war file
      uses: actions/upload-artifact@v2
      with:
        name: stemmarest-war
        path: target/stemmarest.war

  # Push image to Docker.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure build job passes before pushing image.
    needs: build

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Retrieve .war file
        uses: actions/download-artifact@v2
        with:
          name: stemmarest-war
          path: target/stemmarest.war

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dhuniwien/stemmarest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
