# This workflow will run the integration test suite on a pull request
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven - test only

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Graphviz
      run: sudo apt install graphviz
    - name: Add Miredot license
      run: sed -i "s/MIREDOT_LICENSE/${{ secrets.MIREDOT_LICENSE }}/" pom.xml
    - name: Build with Maven
      run: mvn -B test --file pom.xml
